<a href="https://colab.research.google.com/github/prawizard/CE888_Repo/blob/main/Lab_3/bank_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import matplotlib
import pandas as pd
import seaborn as sns
import numpy as np

In [11]:
df=pd.read_csv("bank-additional-full.csv")
# Uploaded the file to session storage. Not fetching using the http link.
print(df.head())
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

   age        job  marital  ... euribor3m nr.employed   y
0   56  housemaid  married  ...     4.857      5191.0  no
1   57   services  married  ...     4.857      5191.0  no
2   37   services  married  ...     4.857      5191.0  no
3   40     admin.  married  ...     4.857      5191.0  no
4   56   services  married  ...     4.857      5191.0  no

[5 rows x 21 columns]


In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2,3,4,5,6,7,8,9,14])], remainder='passthrough')
X=ct.fit_transform(X)

In [16]:
print(X)
print(X.shape)

[[0.0 0.0 0.0 ... -36.4 4.857 5191.0]
 [0.0 0.0 0.0 ... -36.4 4.857 5191.0]
 [0.0 0.0 0.0 ... -36.4 4.857 5191.0]
 ...
 [0.0 0.0 0.0 ... -50.8 1.028 4963.6]
 [0.0 0.0 0.0 ... -50.8 1.028 4963.6]
 [0.0 0.0 0.0 ... -50.8 1.028 4963.6]]
(41188, 63)


In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [19]:
print(y)

[0 0 0 ... 0 1 0]
